CREATE TABLE cards (
  id SERIAL PRIMARY KEY UNIQUE NOT NULL,
  code CHARACTER VARYING(255) NOT NULL,
  content TEXT NOT NULL,
  author CHARACTER VARYING(100) NOT NULL,
  model CHARACTER VARYING(100) NOT NULL,
  created_at TIMESTAMP NOT NULL
  );
