name: Deploy EC2

on:
  workflow_call:

jobs:
  ec2:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      ## IMPORTANTE ##
      # instalar o docker na instancia # sudo yum install docker
      # iniciar o docker # sudo systemctl start docker
      # configurar o aws configure # sudo aws configure
      # definir as permissões para o docker, é essencial para funcionar
      # ex. sudo usermod -aG docker ec2-user
      # ex. sudo chmod 777 /var/run/docker.sock
      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            docker stop cards-api
            echo 'Docker Stoped'
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 497176797028.dkr.ecr.us-east-1.amazonaws.com/cards-api-registry:latest
            echo 'Login OK'
            docker pull 497176797028.dkr.ecr.us-east-1.amazonaws.com/cards-api-registry:latest
            echo 'Download Docker Image OK'
            docker tag 497176797028.dkr.ecr.us-east-1.amazonaws.com/cards-api-registry:latest cards-api:latest
            echo 'Tag Image OK'
            docker rm cards-api
            echo 'Remove old Image OK'
            docker run -p 80:8080 -d --env DB_HOST=${{ secrets.DB_HOST }} --env DB_USER=${{ secrets.DB_USER }} --env DB_PASSWORD=${{ secrets.DB_PASSWORD }} --name cards-api cards-api:latest
