name: Integration - App

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3.13.0
        with:
          distribution: "adopt"
          java-version: 17

      - name: Build the API
        run: mvn clean package

      # esse upload é usado apenas para casos de deploy na EC2
      # para deploys que utilizam a imagem em um registry não precisa dos arquivos
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: Cards API
          path: target

  scan-virus:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Scan for Virus
        run: echo '## Scanning for some virus ...'

  scan-vunerabilities:
    needs: scan-virus
    runs-on: ubuntu-latest

    steps:
      - name: Scan for Vunerabilities
        run: echo '## Scanning for some vunerabilities ...'

  tests:
    needs: scan-vunerabilities
    runs-on: ubuntu-latest

    steps:
      - name: Testing Application
        run: echo '## Testing the application ...'
